name: "Build Zephyr Firmware"

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["*"]
  workflow_dispatch:

concurrency:
  group: ${{ github.ref }}
  cancel-in-progress: true

env:
  ZEPHYR_SDK_INSTALL_DIR: /opt/toolchains

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build for ${{ matrix.board }}
    strategy:
      matrix:
        board: [xiao_esp32c3, xiao_esp32c6]
    container:
      image: ghcr.io/zephyrproject-rtos/ci:v0.27.5

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup West workspace
        run: |
          west init -l .
          west update
          west blobs fetch hal_espressif

      - name: Build firmware
        run: |
          west build -b ${{ matrix.board }}

      - name: Upload firmware
        uses: actions/upload-artifact@v4
        with:
          name: firmware-${{ matrix.board }}
          path: build/zephyr/zephyr.bin
          if-no-files-found: error
